packages:
  - 'packages/*'
  - 'playground/*'
  - 'examples/*'
  - 'apps/*'


catalog:
  'typescript': ^5.7.3
  'vitest': ^3.0.4
  '@vitest/browser': ^3.0.4
  'vite': ^6.0.11
  'unbuild': ^3.3.1
  'lwc': ^8.12.6
  '@lwc/engine-core': ^8.12.6
  '@lwc/engine-dom': ^8.12.6
  '@lwc/engine-server': ^8.12.6
  '@lwc/shared': ^8.12.6
  '@lwc/ssr-runtime': ^8.12.6
  '@lwc/synthetic-shadow': ^8.12.6
  '@lwc/wire-service': ^8.12.6
  '@lwc/rollup-plugin': ^8.12.6
  '@lwc/features': ^8.12.6
