packages:
  - packages/*
  - examples/*
  - playground/*
allowedDeprecatedVersions:
  lightning-base-components: 1.22.3-alpha
requiredScripts:
  - "typecheck"
linkWorkspacePackages: true
shellEmulator: true
registry: https://registry.npmjs.org/
onlyBuiltDependencies:
  - "esbuild"
  - "msw"
  - "simple-git-hooks"

overrides:
  "cross-spawn@>=7.0.0 <7.0.5": ">=7.0.5"
  "nanoid@<3.3.8": ">=3.3.8"
  "esbuild@<=0.24.2": ">=0.25.0"
