name: Publish Any Commit
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'cardoso/vite-plugin-lwc'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Playwright
        run: pnpm exec playwright install chromium

      - name: Test
        run: pnpm test

      - name: Publish
        run: pnpm dlx pkg-pr-new publish --compact './packages/vite-plugin-lwc' './packages/create-lwc' --template './examples/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
